sudo: required
language: python

services:
  - docker

before_script:
  - curl https://cli-assets.heroku.com/install.sh | sh  #install heroku
  - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com  #login to registry.heroku.com 

script:
  - docker build -t registry.heroku.com/$HEROKU_APP/web .

deploy:   
  provider: script
  script: 
    docker push registry.heroku.com/$HEROKU_APP/web;
    heroku container:release web --app $HEROKU_APP
  on:
    branch: main

    